Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  # Use Ansible to create /home/vagrant directory and state.file
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
  end

  # Use Ansible to remove state.file before destroy
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "ansible/remove_playbook.yml"
  end
end
