Vagrant.configure("2") do |config|
  #config.vm.provider "virtualbox"

# Machine 1
  config.vm.define "machine1" do |machine1|
    machine1.vm.box = "hashicorp/bionic64"
    machine1.vm.network "private_network", ip: "192.168.56.101"
    #machine1.vm.hostname = "machine1"
    #machine1.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh"
  end

# Machine 2
  config.vm.define "machine2" do |machine2|
    machine2.vm.box = "fedora/38-cloud-base"
    machine2.vm.network "private_network", #ip: "192.168.56.102"
    #machine2.vm.hostname = "machine2"
    #machine2.vm.network "forwarded_port", guest: 22, host: 2223, id: "ssh"
  end
  

end
